### ISSUE TITLE
Kafka  + LDBC Driver Integration

### ISSUE THREAD

**Issue by anilpacaci** [anilpacaci/graph-benchmarking#4]
LDBC Driver generates update objects. These needs to be serialised and pushed into an update queue. Then each implementation specific consumer will consume update objects and generate implementation specific update query. (We already have gremlin consumer, we need to make gremlin producer generic producer)

**Comment by aliceranzhou** [comment]
- wrapper for KafkaProducer
- OperationExecutor for consumer
- add consumer running to WorkloadRunner `___.execute() in WR.run()`
- finish Kryo Serialization

**Comment by aliceranzhou** [comment]
two modes for driver:
- update directly into db
- kafka update
=> flag in DbConnectionState or smth

**Comment by aliceranzhou** [comment]
ConsoleAndFileDriverConfiguration

**Comment by aliceranzhou** [comment]
OperationExecutorService
  OperationExecutorServiceThread
    Kafka Consumer
OperationExecutor
  ContextRetriever (w/o StreamDefinition)

**Comment by aliceranzhou** [comment]
Serialization done, executor services implemented. 

Remaining: implement two modes for driver

**Comment by aliceranzhou** [comment]
single kafka queue impl done
